### PR TITLE
Updates to latest results

### PR DESCRIPTION
**Pull request by wwieder**
This PR has some features that allow us to processes more sites with incomplete simulation times.
Other changes are mainly cosmetic or point to my simulations (not the ones you were pointing to, Negin).

### CODE REVIEW

**Comment by negin513** [comment]
@wwieder I have merged in @TeaganKing's PR but I cannot merge yours since it has several conflicts. Can you review the conflicts and resolve them?

**Review by wwieder — COMMENTED** [review]
I don't know how to resolve diffs here, sorry.

**Comment by wwieder** [comment]
@negin513 do you have suggestions on how to do this?  In other repos i've used nbviewer, but I can't figure out how to do this here.  Do you have suggestions?

**Comment by negin513** [comment]
Here are the instructions provided by git on resolving the merge conflicts. 
https://capture.dropbox.com/ozp5dczYDbyWDzuy

This is on your branch so I don't have any way to resole it and push to it unless I am a contributor on your repository fork. 

It should be possible to make a PR directly to the NCAR level repo as well: https://github.com/NCAR/neon_scripts

**Comment by negin513** [comment]
It seems like only 4 files have conflicts:
```
notebooks/fig4_timeseries_selected.ipynb
notebooks/fig8_abby_smois.ipynb
notebooks/neon_utils.py
```

**Comment by wwieder** [comment]
I'm still having a hard time visualizing the diffs and not really sure why?  I'll see what I can do...

**Comment by negin513** [comment]
Merge conflict now resolved.

**Pull request merged**
